-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 17:22:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sedb` ;

-- -----------------------------------------------------
-- Schema sedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sedb` DEFAULT CHARACTER SET utf8 ;
USE `sedb` ;

-- -----------------------------------------------------
-- Table `sedb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`user` ;

CREATE TABLE IF NOT EXISTS `sedb`.`user` (
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `fname` VARCHAR(150) NULL,
  `lname` VARCHAR(150) NULL,
  `email` VARCHAR(255) NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`username`));


-- -----------------------------------------------------
-- Table `sedb`.`faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`faculty` ;

CREATE TABLE IF NOT EXISTS `sedb`.`faculty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`department` ;

CREATE TABLE IF NOT EXISTS `sedb`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `faculty_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_department_faculty1_idx` (`faculty_id` ASC),
  CONSTRAINT `fk_department_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `sedb`.`faculty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`branch` ;

CREATE TABLE IF NOT EXISTS `sedb`.`branch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `max_year` VARCHAR(45) NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branch_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_branch_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `sedb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`subject` ;

CREATE TABLE IF NOT EXISTS `sedb`.`subject` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(150) NULL,
  `year` INT NULL,
  `semester` INT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subject_branch1_idx` (`branch_id` ASC),
  CONSTRAINT `fk_subject_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `sedb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`sheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`sheet` ;

CREATE TABLE IF NOT EXISTS `sedb`.`sheet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `title` VARCHAR(255) NULL,
  `term` VARCHAR(45) NULL,
  `subject_id` VARCHAR(45) NULL,
  `branch_id` INT NULL,
  `department_id` INT NULL,
  `faculty_id` INT NULL,
  `create_by` VARCHAR(30) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_sheet_user_idx` (`create_by` ASC),
  INDEX `fk_sheet_faculty1_idx` (`faculty_id` ASC),
  INDEX `fk_sheet_department1_idx` (`department_id` ASC),
  INDEX `fk_sheet_branch1_idx` (`branch_id` ASC),
  INDEX `fk_sheet_subject1_idx` (`subject_id` ASC),
  FULLTEXT INDEX `title` (`title` ASC),
  CONSTRAINT `fk_sheet_user`
    FOREIGN KEY (`create_by`)
    REFERENCES `sedb`.`user` (`username`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheet_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `sedb`.`faculty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheet_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `sedb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheet_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `sedb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheet_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `sedb`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`sheet_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`sheet_image` ;

CREATE TABLE IF NOT EXISTS `sedb`.`sheet_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sheet_id` INT NOT NULL,
  `order` INT NULL,
  `path` VARCHAR(2083) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_image_sheet1_idx` (`sheet_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_image_sheet1`
    FOREIGN KEY (`sheet_id`)
    REFERENCES `sedb`.`sheet` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`sheet_pdf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`sheet_pdf` ;

CREATE TABLE IF NOT EXISTS `sedb`.`sheet_pdf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sheet_id` INT NOT NULL,
  `path` VARCHAR(2083) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_pdf_sheet1_idx` (`sheet_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pdf_sheet1`
    FOREIGN KEY (`sheet_id`)
    REFERENCES `sedb`.`sheet` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
